version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      compose_back_net:
        aliases:
          - db    
          - comment_db
          - post_db
  ui:
#    build: ./ui
    image: ${USERNAME}/ui:${IMAGE_VER}
    ports:
      - ${HOST_PORT}:${PUBLIC_PORT}/tcp
    networks:
      - compose_front_net
  post:
#    build: ./post-py
    image: ${USERNAME}/post:${IMAGE_VER}
    networks:
      compose_back_net:
        aliases:
          - post 
      compose_front_net:
        aliases:
          - post
  comment:
#    build: ./comment
    image: ${USERNAME}/comment:${IMAGE_VER}
    networks:
      compose_back_net:
        aliases:
          - comment
      compose_front_net:
        aliases:
          - comment

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - compose_back_net
      - compose_front_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - compose_back_net
      - compose_front_net

volumes:
  post_db:
  prometheus_data:

networks:
  compose_back_net:
  compose_front_net:
