version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      compose_back_net:
        aliases:
          - db    
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${IMAGE_VER}
    ports:
      - ${HOST_PORT}:${PUBLIC_PORT}/tcp
    networks:
      - compose_front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${IMAGE_VER}
    networks:
      - compose_back_net
      - compose_front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${IMAGE_VER}
    networks:
      - compose_back_net
      - compose_front_net

volumes:
  post_db:

networks:
  compose_back_net:
  compose_front_net:
